var 
getallcabinetdata =
{"code":200,"status":"ok","results":{"cabinetTitle":"News","cabinetDescription":"We will add a description here for the main opening screen","items":[{"id":"6","tab_text":"Jobs","title":"Squirrel Jobs","subtitle":"Web App","description":"will add details here blah blah blah will add details here blah blah blah will add details here blah blah blah","image_url":"http://www.graphicsfuel.com/wp-content/uploads/2016/01/harcover-book-mockup.jpg","add_date":"2016-06-14 11:16:39"},{"id":"5","tab_text":"DA","title":"Digital Anarchy","subtitle":"E-Commerce Platform","description":"will add details here blah blah blah will add details here blah blah blah will add details here blah blah blah","image_url":"http://www.graphicsfuel.com/wp-content/uploads/2016/01/standing-business-cards-mockup.jpg","add_date":"2016-06-14 11:16:27"},{"id":"4","tab_text":"Inflo","title":"Inflo.IO","subtitle":"Design Services","description":"will add details here blah blah blah will add details here blah blah blah will add details here blah blah blah","image_url":"https://www.mockupworld.co/wp-content/uploads/edd/2015/09/Free-Macbook-Pro-PSD-Mockup.jpg","add_date":"2016-06-14 11:16:16"},{"id":"3","tab_text":"Design","title":"Design","subtitle":"Services ","description":"will add details here blah blah blah will add details here blah blah blah will add details here blah blah blah","image_url":"http://www.webdesigndev.com/wp-content/uploads/2015/01/Cutout-Logo-MockUp-e1421779051582.jpg","add_date":"2016-06-14 11:16:05"},{"id":"2","tab_text":"IAG","title":"It's A Grind","subtitle":"Mobile App","description":"will add details here blah blah blah will add details here blah blah blah will add details here blah blah blah","image_url":"https://d13yacurqjgara.cloudfront.net/users/599747/screenshots/2361951/dribbble.jpg","add_date":"2016-06-14 11:12:29"}]}}
,
getphonepopupdata = 
{"code":200,"status":"ok","results":{name : "Name", email : "E-MAIL", phone : "phone"}}
,
getAllPortfolioData = 
{"code":200,"status":"ok","results":{"itemCount":3,"items":[{"id":"1","title":"title1","description":"Description 1","backColor1":"123456","backColor2":"234567","backColor3":"345678","showImageTitle":"1","image1URL":"http://www.google.com/1","image1Title":"Project1 Image 1","image2URL":"http://www.graphicsfuel.com/wp-content/uploads/2016/01/harcover-book-mockup.jpg","image2Title":"Project1 Image 2","image3URL":"http://www.google.com/3","image3Title":"Project1 Image 3"},{"id":"2","title":"title2","description":"Description 2","backColor1":"098765","backColor2":"987654","backColor3":"876543","showImageTitle":"1","image1URL":"http://www.yahoo.com/1","image1Title":"Project2 Image 1","image2URL":"http://www.graphicsfuel.com/wp-content/uploads/2016/01/standing-business-cards-mockup.jpg","image2Title":"Project2 Image 2","image3URL":"http://www.yahoo.com/3","image3Title":"Project2 Image 3"},{"id":"3","title":"title3","description":"Description 3","backColor1":"567890","backColor2":"678901","backColor3":"789012","showImageTitle":"0","image1URL":"http://www.bing.com/1","image1Title":"Project3 Image 1","image2URL":"https://www.mockupworld.co/wp-content/uploads/edd/2015/09/Free-Macbook-Pro-PSD-Mockup.jpg","image2Title":"Project3 Image 2","image3URL":"http://www.bing.com/3","image3Title":"Project3 Image 3"}]}}
,
getPortfolioTitle = {"title":"Portfolio title", "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "backColor1":"123456", "backColor2":"234567" }

;
