 var json = [ {"vol" : 25},
      				{"vol" : 4.7}],//data fot infographic
    iLook = {R : 325, w : 105 //R - out radius in px, w - width
             ,color : '#6D9EEB' //color of outer data circle
			},
txtFirst = ["In the spring of 2008, WSSC began using electricity generated by a wind farm in southwestern Pennsylvania"],
txtSec = ["2015 US wind electricity generation was 4.7% of total electricity production"],
txtThr = ["WSSC 25% of WSSC's total total 2015 electricity consumption is from direct wind generation, over 5 times the national rate of wind production"]
;
var phases = {'one' : 1000 //dashdrawing turbine + reveal text1   
            , 'two' : 1000 //dashdrawing blades
            , 'three' : 1000 //blades growing
            , 'four' : 4000 // appiar text2 and inner donat 
            , 'five' : 4000 //rotation. appiar outer donat and text3
            , 'six' : 2000 //infograph move, draft disappiar, photo appiar
            };
var width = 2550,//size of croped photo
    height = 1207,//size of croped photo
    cr = {x:2106, y:467},//center of rotation
    tau = 2 * Math.PI,//360 deg
    newPlace = {x : (width-cr.x)*0.9, y : cr.y*1.2, scale : 1}; //where infographic move before animation

